remote_theme: pmarsceill/just-the-docs

labtitle: Steph's µLab
laburl: "https://github.com/m1cr0lab"
labstart: 2020

title: ESP32 Remote Control with WebSocket
description: This tutorial details the use of WebSocket to remotely interact with an ESP32 that exposes a web application through an HTTP server. The WebSocket protocol opens a two-way communication channel between the client browser and the HTTP server run by the ESP32. With this API you can send messages to a server and receive its responses on an event-driven basis without having to go to the server for a response.
author: Stéphane Calderoni
xtags: [ESP32, SPIFFS, WebServer, WebSocket, JSON]
date: 2020-04-25

defaults:
  - scope:
      path: ""
    values:
      image:
        path: logo/thumbnail.png
        width: 128
        height: 128

permalink: pretty
timezone: Indian/Reunion
search_enabled: true
heading_anchors: true

exclude: [Readme.md, README.md, LICENSE]

# Google Analytics Tracking
ga_tracking: UA-1998450-4